sudo: required
services:
    - docker

script:
    - docker build -t mannydesigns/node .
    - docker images mannydesigns/node

before_deploy: 
    - docker login -u cercico -p Reddeers..25

deploy:
    provider: script
    script : docker push "mannydesigns/node:v1.0.0"
    on:
        branch: master